#
# SmartSeq3 config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content


custom_data:
    stats:
      file_format: 'csv'
      section_name: 'General Metrics'
      description: 'Result summaries of each cell. The number of fragments is the number of cDNA sequenced. It is the sequencing depth. The percentage of UMIs is the proportion of fragments having tag-UMI-GGG pattern within their sequences. Alignment is made on non UMI and UMI reads. The assignment is made on correctly aligned reads. Gene counts is calculating using all the reads or only UMI reads to have a cleaner count.'
      plot_type: 'table'
      pconfig:
          namespace: 'stats'
          id: 'stats'
          title: 'General Statistics'
          save_file: true
          col1_header: 'Sample ID'
      headers:
          Sample_name:
            title: 'Sample Name'
            scale: false
            placement: 2000
          Number_of_fragments:
            title: 'Total Fragments'
            scale: 'YlGnBu'
            format: '{:,.0f}'
            placement: 3000
          Percent_UMIs:
            title: 'UMI reads (%)'
            min: 0
            max: 100
            scale: 'Purples'
            suffix: '%'
            format: '{:,.1f}'
            placement: 4000
          Percent_Aligned:
            title: 'Aligned (%)'
            min: 0
            max: 100
            scale: 'Greens'
            suffix: '%'
            format: '{:,.1f}'
            placement: 5000
          Percent_Assigned:
            title: 'Assigned (%)'
            min: 0
            max: 100
            scale: 'YlGn'
            suffix: '%'
            format: '{:,.1f}'
            placement: 6000
          Number_of_UMIs:
            title: 'UMIs'
            scale: 'Oranges'
            format: '{:,.0f}'
            placement: 7000
          Number_of_genes_umi:
            title: 'Genes (umis)'
            scale: 'RdPu'
            format: '{:,.0f}'
            placement: 8000
          Percent_dedup:
            title: '%Dedup'
            scale: 'RdPu'
            format: '{:,.0f}'
            placement: 9000
          Number_of_reads:
            title: 'Reads'
            scale: 'Oranges'
            format: '{:,.0f}'
            placement: 10000
          Number_of_genes_read:
            title: 'Genes (reads)'
            scale: 'RdPu'
            format: '{:,.0f}'
            placement: 20000

    final:
      file_format: 'csv'
      section_name: 'Mapping summary'
      description: '{desc} Overview of mapping steps corresponding to alignment & assignment. The alignment is done on all reads (UMI and non UMI reads). Correct reads are aligned on the genome and assigned to a gene.'
      plot_type: 'bargraph'
      pconfig:
        id: 'final'
        title: 'Mapping summary'

    umiPerGene: 
      file_format: 'csv'
      section_name: 'Expression level'
      title: 'Number of UMIs per gene'
      description: 'Distribution of the number of UMIs per gene in each sample. Genes having more than 70 UMIs (x axis) are not shown. Most genes have between one and 10 UMIs and a bend can be observed around 5.'
      plot_type: 'linegraph'
      pconfig:
        id: 'umiPerGene'
        title: ''
        xlab: 'Number of UMIs per gene'
        xmax: 70
        ylab: 'Number of genes'
        #xLog: True
        #logswitch: True
        #logswitch_active: True
        #logswitch_label: 'Log10'
        #reversedStacks: True

    nbGene_perCell: 
      file_format: 'csv'
      section_name: 'Library complexity'
      title: 'Number of genes per cell'
      description: 'Genes are those found in the UMI matrices (non UMI reads are not take into account).'
      plot_type: 'bargraph'
      pconfig:
        id: 'nbGene_perCell'
        title: 'Number of genes per cell'

    nbUmi_perCell: 
      file_format: 'csv'
      section_name: 'Number of UMIs per cell'
      plot_type: 'bargraph'
      pconfig:
        id: 'nbUmi_perCell'
        title: 'Number of UMIs per cell'
        
    ratio: 
      file_format: 'csv'
      section_name: 'Library complexity'
      section_name: 'Number of genes & UMIs per cell'
      description: 'A scatter plot of the ratio of the number of genes and UMIs per cell allow an easy representation of a cell composition.'
      plot_type: 'scatter'
      pconfig:
        id: 'ratio'
        title: 'Number of genes and UMIs per cell'
        xlab: 'Number of UMIs'
        ylab: 'Number of genes'

    mt: 
      file_format: 'csv'
      section_name: 'Cell viability'
      title: '% Mitochondrial RNAs per cell'
      description: 'Percentage of mitochondrial RNAs is a cell viability marker. It varies according to your cell type (e.g cell line, primary cells, etc.). Here, only UMI reads are take into account.'
      plot_type: 'scatter'
      pconfig:
        id: 'mt'
        title: 'Percentage of mitochondrial RNAs per cell'
        xlab: 'Number of genes'
        ylab: '% mitochondrial RNAs'

    gene_saturation:
       file_format: 'tsv'
       section_name: 'Gene-based saturation'
       description: 'Plot showing the number of detected genes for a given set of subsampled values.'
       plot_type: 'linegraph'
       pconfig:
            namespace: 'gene saturation'
            id: 'genesaturation'
            title: 'Gene-based Saturation'
            ylab: 'Number of detected genes'
            xlab: 'Number of UMIs (per thousand)'

    umi_deduplication:
       file_format: 'csv'
       section_name: 'PCR deduplication'
       description: 'Plot showing the number of UMIs before and after PCR removal.'
       plot_type: 'scatter'
       pconfig:
            namespace: 'umi deduplication'
            id: 'umideduplication'
            title: 'Deduplication'
            ylab: 'Total UMIs'
            xlab: 'Deduplicated UMIs'


sp:
  stats:
      fn: 'table_mqc.stats'
  final:
      fn: 'final_mqc.stats'
  umiPerGene:
      fn: '*_HistUMIperGene_mqc.csv'
  nbGene_perCell:
      fn: 'nbGenePerCell.csv'
  nbUmi_perCell:
      fn: 'nbUMIPerCell.csv'
  ratio:
      fn: 'RatioPerCell.csv'
  mt:
      fn: 'MtGenePerCell.csv'
  gene_saturation:
      fn: '*gcurve.txt'
  umi_deduplication:
      fn: '*_Umi_dedup_summary.log'



###############################
## Modules 

module_order:
  - cutadapt
  - star
  - featurecounts
  - preseq:
     name: 'Sequencing Complexity'
     info: 'Estimates the complexity of a library, showing how many additional unique reads are sequenced for increasing total read count. A shallow curve indicates complexity saturation. The dashed line shows a perfectly complex library where total reads = unique reads.'
  - deeptools
  - rseqc

#############################
## Display

report_section_order:
  # summary table
  stats:
    order: 850
  # mapping:
  final:
    order: 800
  star:
    order: 750
  featurecounts:
    order: 700
  cutadapt:
    order: 650
  rseqc:
    order: 550
  # cell analysis
  umiPerGene:
    order: 500
  nbGene_perCell:
    order: 450
  nbUmi_perCell:
    order: 400
  ratio:
    order: 350
  mt:
    order: 300
  software_versions:
    order: -1500
  summary:
    order: -2000

plots_force_interactive: True
